SET FOREIGN_KEY_CHECKS = 0;

-- azenz_commercial_1.p_permissions definition

CREATE TABLE `p_permissions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(100) NOT NULL,
  `module` varchar(100) NOT NULL,
  `action` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  UNIQUE KEY `uq_permission_module_action` (`module`,`action`),
  KEY `idx_module` (`module`),
  KEY `idx_action` (`action`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_roles definition

CREATE TABLE `p_roles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `display_name` varchar(150) NOT NULL,
  `description` text DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `idx_name` (`name`),
  KEY `idx_active` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_types_documents definition

CREATE TABLE `p_types_documents` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_type_document` varchar(50) NOT NULL,
  `nom_type_document` varchar(100) NOT NULL,
  `domaine` enum('VENTE','ACHAT','STOCK','INTERNE') NOT NULL,
  `sens_stock` enum('AUCUN','ENTREE','SORTIE') NOT NULL DEFAULT 'AUCUN',
  `impacte_stock` tinyint(1) NOT NULL DEFAULT 0,
  `impacte_reglement` tinyint(1) NOT NULL DEFAULT 0,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_type_document` (`code_type_document`),
  KEY `idx_domaine` (`domaine`),
  KEY `idx_sens_stock` (`sens_stock`),
  KEY `idx_actif` (`actif`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_numerotation_documents definition

CREATE TABLE `p_numerotation_documents` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `type_document_id` bigint(20) unsigned NOT NULL,
  `prefixe` varchar(20) NOT NULL,
  `annee` int(10) unsigned NOT NULL,
  `dernier_numero` varchar(20) NOT NULL,
  `longueur_numero` int(10) unsigned NOT NULL DEFAULT 4,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_numerotation_type_annee` (`type_document_id`,`annee`),
  KEY `idx_type_document` (`type_document_id`),
  KEY `idx_annee` (`annee`),
  KEY `idx_actif` (`actif`),
  CONSTRAINT `fk_numerotation_type_document` FOREIGN KEY (`type_document_id`) REFERENCES `p_types_documents` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_role_permissions definition

CREATE TABLE `p_role_permissions` (
  `role_id` bigint(20) unsigned NOT NULL,
  `permission_id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `idx_permission` (`permission_id`),
  CONSTRAINT `fk_role_permissions_permission` FOREIGN KEY (`permission_id`) REFERENCES `p_permissions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_role_permissions_role` FOREIGN KEY (`role_id`) REFERENCES `p_roles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_utilisateurs definition

CREATE TABLE `p_utilisateurs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `nom_utilisateur` varchar(100) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `code_utilisateur` varchar(50) NOT NULL,
  `email` varchar(255) NOT NULL,
  `telephone` varchar(30) DEFAULT NULL,
  `mot_de_passe_hash` varchar(255) NOT NULL,
  `est_administrateur` tinyint(1) NOT NULL DEFAULT 0,
  `date_mot_de_passe` datetime DEFAULT NULL,
  `date_derniere_connexion` datetime DEFAULT NULL,
  `statut_mot_de_passe` enum('ACTIF','A_CHANGER','EXPIRE','BLOQUE') NOT NULL DEFAULT 'ACTIF',
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `tentatives_connexion` int(10) unsigned NOT NULL DEFAULT 0,
  `date_blocage` datetime DEFAULT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `nom_utilisateur` (`nom_utilisateur`),
  UNIQUE KEY `code_utilisateur` (`code_utilisateur`),
  UNIQUE KEY `email` (`email`),
  KEY `fk_utilisateurs_createur` (`cree_par`),
  KEY `fk_utilisateurs_modificateur` (`modifie_par`),
  KEY `fk_utilisateurs_supprimeur` (`supprime_par`),
  KEY `idx_nom_utilisateur` (`nom_utilisateur`),
  KEY `idx_code_utilisateur` (`code_utilisateur`),
  KEY `idx_email` (`email`),
  KEY `idx_actif` (`actif`),
  KEY `idx_statut_mot_de_passe` (`statut_mot_de_passe`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_utilisateurs_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_utilisateurs_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_utilisateurs_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.journaux_audit definition

CREATE TABLE `journaux_audit` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `utilisateur_id` bigint(20) unsigned DEFAULT NULL,
  `action` enum('CREATE','UPDATE','DELETE','RESTORE','LOGIN','LOGOUT','VALIDATE','CANCEL','PRINT','EXPORT') NOT NULL,
  `table_cible` varchar(100) NOT NULL,
  `enregistrement_id` bigint(20) unsigned DEFAULT NULL,
  `ancienne_valeur` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`ancienne_valeur`)),
  `nouvelle_valeur` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`nouvelle_valeur`)),
  `description` varchar(255) DEFAULT NULL,
  `adresse_ip` varchar(45) DEFAULT NULL,
  `hostname` varchar(500) DEFAULT NULL,
  `date_action` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_utilisateur` (`utilisateur_id`),
  KEY `idx_action` (`action`),
  KEY `idx_table_cible` (`table_cible`),
  KEY `idx_enregistrement` (`table_cible`,`enregistrement_id`),
  KEY `idx_date_action` (`date_action`),
  CONSTRAINT `fk_journaux_audit_utilisateur` FOREIGN KEY (`utilisateur_id`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=201 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_caisses definition

CREATE TABLE `p_caisses` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_caisse` varchar(50) NOT NULL,
  `nom_caisse` varchar(100) NOT NULL,
  `type_caisse` enum('CAISSE','BANQUE','TERMINAL_PAIEMENT','AUTRE') NOT NULL DEFAULT 'CAISSE',
  `banque_nom` varchar(150) DEFAULT NULL,
  `numero_compte` varchar(100) DEFAULT NULL,
  `iban` varchar(100) DEFAULT NULL,
  `rib` varchar(100) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_caisse` (`code_caisse`),
  KEY `fk_caisses_createur` (`cree_par`),
  KEY `fk_caisses_modificateur` (`modifie_par`),
  KEY `fk_caisses_supprimeur` (`supprime_par`),
  KEY `idx_nom_caisse` (`nom_caisse`),
  KEY `idx_type_caisse` (`type_caisse`),
  KEY `idx_actif` (`actif`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_caisses_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_caisses_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_caisses_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_depots definition

CREATE TABLE `p_depots` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_depot` varchar(50) NOT NULL,
  `nom_depot` varchar(100) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `adresse` varchar(500) DEFAULT NULL,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_depot` (`code_depot`),
  KEY `fk_depots_createur` (`cree_par`),
  KEY `fk_depots_modificateur` (`modifie_par`),
  KEY `fk_depots_supprimeur` (`supprime_par`),
  KEY `idx_nom_depot` (`nom_depot`),
  KEY `idx_actif` (`actif`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_depots_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_depots_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_depots_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_devises definition

CREATE TABLE `p_devises` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_devise` varchar(10) NOT NULL,
  `nom_devise` varchar(100) NOT NULL,
  `symbole` varchar(10) DEFAULT NULL,
  `devise_principale` tinyint(1) NOT NULL DEFAULT 0,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_devise` (`code_devise`),
  KEY `fk_devises_createur` (`cree_par`),
  KEY `fk_devises_modificateur` (`modifie_par`),
  KEY `fk_devises_supprimeur` (`supprime_par`),
  KEY `idx_nom_devise` (`nom_devise`),
  KEY `idx_devise_principale` (`devise_principale`),
  KEY `idx_actif` (`actif`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_devises_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_devises_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_devises_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_modes_reglement definition

CREATE TABLE `p_modes_reglement` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_mode_reglement` varchar(50) NOT NULL,
  `nom_mode_reglement` varchar(100) NOT NULL,
  `type_mode` enum('ESPECE','CHEQUE','VIREMENT','CARTE','EFFET','AVOIR','AUTRE') NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `requiert_banque` tinyint(1) NOT NULL DEFAULT 0,
  `requiert_numero_piece` tinyint(1) NOT NULL DEFAULT 0,
  `requiert_date_echeance` tinyint(1) NOT NULL DEFAULT 0,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_mode_reglement` (`code_mode_reglement`),
  KEY `fk_modes_reglement_createur` (`cree_par`),
  KEY `fk_modes_reglement_modificateur` (`modifie_par`),
  KEY `fk_modes_reglement_supprimeur` (`supprime_par`),
  KEY `idx_nom_mode_reglement` (`nom_mode_reglement`),
  KEY `idx_type_mode` (`type_mode`),
  KEY `idx_actif` (`actif`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_modes_reglement_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_modes_reglement_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_modes_reglement_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_statuts_documents definition

CREATE TABLE `p_statuts_documents` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_statut` varchar(50) NOT NULL,
  `nom_statut` varchar(100) NOT NULL,
  `type_document_id` bigint(20) unsigned NOT NULL,
  `ordre_affichage` int(11) NOT NULL DEFAULT 0,
  `couleur` varchar(30) DEFAULT NULL,
  `document_verrouille` tinyint(1) NOT NULL DEFAULT 0,
  `impacte_stock` tinyint(1) NOT NULL DEFAULT 0,
  `impacte_reglement` tinyint(1) NOT NULL DEFAULT 0,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_statut_type_code` (`type_document_id`,`code_statut`),
  KEY `fk_statuts_documents_createur` (`cree_par`),
  KEY `fk_statuts_documents_modificateur` (`modifie_par`),
  KEY `idx_type_document` (`type_document_id`),
  KEY `idx_ordre_affichage` (`ordre_affichage`),
  KEY `idx_actif` (`actif`),
  CONSTRAINT `fk_statuts_documents_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_statuts_documents_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_statuts_documents_type` FOREIGN KEY (`type_document_id`) REFERENCES `p_types_documents` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_tvas definition

CREATE TABLE `p_tvas` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_tva` varchar(50) NOT NULL,
  `nom_tva` varchar(100) NOT NULL,
  `taux` decimal(6,3) NOT NULL DEFAULT 0.000,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_tva` (`code_tva`),
  KEY `fk_tvas_createur` (`cree_par`),
  KEY `fk_tvas_modificateur` (`modifie_par`),
  KEY `fk_tvas_supprimeur` (`supprime_par`),
  KEY `idx_nom_tva` (`nom_tva`),
  KEY `idx_taux` (`taux`),
  KEY `idx_actif` (`actif`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_tvas_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tvas_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tvas_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_unites definition

CREATE TABLE `p_unites` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_unite` varchar(50) NOT NULL,
  `nom_unite` varchar(100) NOT NULL,
  `symbole` varchar(20) DEFAULT NULL,
  `type_unite` enum('QUANTITE','POIDS','VOLUME','LONGUEUR','SURFACE','TEMPS','AUTRE') NOT NULL DEFAULT 'QUANTITE',
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_unite` (`code_unite`),
  KEY `fk_unites_createur` (`cree_par`),
  KEY `fk_unites_modificateur` (`modifie_par`),
  KEY `fk_unites_supprimeur` (`supprime_par`),
  KEY `idx_nom_unite` (`nom_unite`),
  KEY `idx_type_unite` (`type_unite`),
  KEY `idx_actif` (`actif`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_unites_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_unites_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_unites_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_users_roles definition

CREATE TABLE `p_users_roles` (
  `user_id` bigint(20) unsigned NOT NULL,
  `role_id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`user_id`,`role_id`),
  KEY `idx_role` (`role_id`),
  CONSTRAINT `fk_users_roles_role` FOREIGN KEY (`role_id`) REFERENCES `p_roles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_users_roles_user` FOREIGN KEY (`user_id`) REFERENCES `p_utilisateurs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_familles definition

CREATE TABLE `d_familles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_famille` varchar(100) NOT NULL,
  `nom_famille` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `type_famille` enum('PRODUIT','SERVICE','NUMERIQUE','MATIERE_PREMIERE') NOT NULL,
  `suivi_stock` tinyint(1) NOT NULL DEFAULT 1,
  `mode_valorisation_stock` enum('CMUP','FIFO','LIFO','LOT','SN','FEFO','AUCUN') NOT NULL DEFAULT 'CMUP',
  `tva_id` bigint(20) unsigned DEFAULT NULL,
  `gestion_lot` tinyint(1) NOT NULL DEFAULT 0,
  `gestion_numero_serie` tinyint(1) NOT NULL DEFAULT 0,
  `unite_id` bigint(20) unsigned DEFAULT NULL,
  `depot_id` bigint(20) unsigned DEFAULT NULL,
  `exclure_statistiques` tinyint(1) NOT NULL DEFAULT 0,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_famille` (`code_famille`),
  KEY `fk_familles_createur` (`cree_par`),
  KEY `fk_familles_modificateur` (`modifie_par`),
  KEY `fk_familles_supprimeur` (`supprime_par`),
  KEY `idx_type_famille` (`type_famille`),
  KEY `idx_tva` (`tva_id`),
  KEY `idx_unite` (`unite_id`),
  KEY `idx_depot` (`depot_id`),
  KEY `idx_actif` (`actif`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_familles_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_familles_depot` FOREIGN KEY (`depot_id`) REFERENCES `p_depots` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_familles_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_familles_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_familles_tva` FOREIGN KEY (`tva_id`) REFERENCES `p_tvas` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_familles_unite` FOREIGN KEY (`unite_id`) REFERENCES `p_unites` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_tiers definition

CREATE TABLE `d_tiers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_tiers` varchar(50) NOT NULL,
  `raison_sociale` varchar(255) NOT NULL,
  `nom_commercial` varchar(255) DEFAULT NULL,
  `type_tiers` enum('CLIENT','FOURNISSEUR','PROSPECT','TRANSPORTEUR','AUTRE') NOT NULL,
  `contact_principal` varchar(255) DEFAULT NULL,
  `telephone` varchar(30) DEFAULT NULL,
  `telephone_secondaire` varchar(30) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `site_web` varchar(255) DEFAULT NULL,
  `adresse` varchar(500) DEFAULT NULL,
  `code_postal` varchar(20) DEFAULT NULL,
  `ville` varchar(100) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  `pays` varchar(100) DEFAULT 'Maroc',
  `identifiant_fiscal` varchar(100) DEFAULT NULL,
  `ice` varchar(50) DEFAULT NULL,
  `rc` varchar(100) DEFAULT NULL,
  `patente` varchar(100) DEFAULT NULL,
  `cnss` varchar(100) DEFAULT NULL,
  `tva_id` bigint(20) unsigned DEFAULT NULL,
  `activite` varchar(255) DEFAULT NULL,
  `plafond_credit` decimal(18,2) NOT NULL DEFAULT 0.00,
  `delai_paiement_jours` int(10) unsigned NOT NULL DEFAULT 0,
  `devise_id` bigint(20) unsigned DEFAULT NULL,
  `mode_paiement_id` bigint(20) unsigned DEFAULT NULL,
  `code_edi` varchar(100) DEFAULT NULL,
  `type_edi` varchar(100) DEFAULT NULL,
  `facture_electronique` tinyint(1) NOT NULL DEFAULT 0,
  `emission_fe` tinyint(1) NOT NULL DEFAULT 0,
  `application_fe` varchar(100) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_tiers` (`code_tiers`),
  KEY `fk_tiers_mode_paiement` (`mode_paiement_id`),
  KEY `fk_tiers_createur` (`cree_par`),
  KEY `fk_tiers_modificateur` (`modifie_par`),
  KEY `fk_tiers_supprimeur` (`supprime_par`),
  KEY `idx_type_tiers` (`type_tiers`),
  KEY `idx_raison_sociale` (`raison_sociale`),
  KEY `idx_ville` (`ville`),
  KEY `idx_tva` (`tva_id`),
  KEY `idx_devise` (`devise_id`),
  KEY `idx_actif` (`actif`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_tiers_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tiers_devise` FOREIGN KEY (`devise_id`) REFERENCES `p_devises` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tiers_mode_paiement` FOREIGN KEY (`mode_paiement_id`) REFERENCES `p_modes_reglement` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tiers_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tiers_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tiers_tva` FOREIGN KEY (`tva_id`) REFERENCES `p_tvas` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_utilisateur_depots definition

CREATE TABLE `d_utilisateur_depots` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `utilisateur_id` bigint(20) unsigned NOT NULL,
  `depot_id` bigint(20) unsigned NOT NULL,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_utilisateur_depot` (`utilisateur_id`,`depot_id`),
  KEY `fk_utilisateur_depots_createur` (`cree_par`),
  KEY `fk_utilisateur_depots_modificateur` (`modifie_par`),
  KEY `fk_utilisateur_depots_supprimeur` (`supprime_par`),
  KEY `idx_utilisateur` (`utilisateur_id`),
  KEY `idx_depot` (`depot_id`),
  CONSTRAINT `fk_utilisateur_depots_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_utilisateur_depots_depot` FOREIGN KEY (`depot_id`) REFERENCES `p_depots` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_utilisateur_depots_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_utilisateur_depots_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_utilisateur_depots_utilisateur` FOREIGN KEY (`utilisateur_id`) REFERENCES `p_utilisateurs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.p_informations_societe definition

CREATE TABLE `p_informations_societe` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `raison_sociale` varchar(255) NOT NULL,
  `nom_commercial` varchar(255) DEFAULT NULL,
  `activite` varchar(255) DEFAULT NULL,
  `identifiant_fiscal` varchar(100) DEFAULT NULL,
  `ice` varchar(50) DEFAULT NULL,
  `rc` varchar(100) DEFAULT NULL,
  `patente` varchar(100) DEFAULT NULL,
  `cnss` varchar(100) DEFAULT NULL,
  `adresse` varchar(500) DEFAULT NULL,
  `code_postal` varchar(20) DEFAULT NULL,
  `ville` varchar(100) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  `pays` varchar(100) NOT NULL DEFAULT 'Maroc',
  `telephone` varchar(30) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `site_web` varchar(255) DEFAULT NULL,
  `logo_url` varchar(500) DEFAULT NULL,
  `devise_id` bigint(20) unsigned DEFAULT NULL,
  `tva_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_devise` (`devise_id`),
  KEY `idx_tva` (`tva_id`),
  CONSTRAINT `fk_infos_societe_devise` FOREIGN KEY (`devise_id`) REFERENCES `p_devises` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_infos_societe_tva` FOREIGN KEY (`tva_id`) REFERENCES `p_tvas` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_adresses_livraison definition

CREATE TABLE `d_adresses_livraison` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tier_id` bigint(20) unsigned NOT NULL,
  `nom_adresse` varchar(150) NOT NULL,
  `adresse` varchar(500) NOT NULL,
  `utilisateur_id` varchar(150) DEFAULT NULL,
  `telephone` varchar(30) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `code_postal` varchar(20) DEFAULT NULL,
  `ville` varchar(100) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  `pays` varchar(100) NOT NULL DEFAULT 'Maroc',
  `instructions_livraison` text DEFAULT NULL,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_adresse_createur` (`cree_par`),
  KEY `fk_adresse_modificateur` (`modifie_par`),
  KEY `fk_adresse_supprimeur` (`supprime_par`),
  KEY `idx_tier` (`tier_id`),
  KEY `idx_ville` (`ville`),
  KEY `idx_actif` (`actif`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_adresse_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_adresse_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_adresse_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_adresse_tiers` FOREIGN KEY (`tier_id`) REFERENCES `d_tiers` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_articles definition

CREATE TABLE `d_articles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_article` varchar(100) NOT NULL,
  `designation` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `famille_id` bigint(20) unsigned DEFAULT NULL,
  `type_article` enum('PRODUIT','SERVICE','NUMERIQUE','MATIERE_PREMIERE') NOT NULL,
  `unite_id` bigint(20) unsigned DEFAULT NULL,
  `unite_secondaire_id` bigint(20) unsigned DEFAULT NULL,
  `prix_achat_ht` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `prix_achat_ttc` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `prix_vente_ht` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `prix_vente_ttc` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `prix_net` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `tva_id` bigint(20) unsigned DEFAULT NULL,
  `suivi_stock` tinyint(1) NOT NULL DEFAULT 1,
  `mode_valorisation_stock` enum('CMUP','FIFO','LIFO','LOT','SN','FEFO','AUCUN') NOT NULL DEFAULT 'CMUP',
  `prix_revient_unitaire` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `quantite_min_stock` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `quantite_max_stock` decimal(18,4) DEFAULT NULL,
  `gestion_lot` tinyint(1) NOT NULL DEFAULT 0,
  `gestion_numero_serie` tinyint(1) NOT NULL DEFAULT 0,
  `article_compose` tinyint(1) NOT NULL DEFAULT 0,
  `interdire_achat` tinyint(1) NOT NULL DEFAULT 0,
  `interdire_vente` tinyint(1) NOT NULL DEFAULT 0,
  `interdire_commande` tinyint(1) NOT NULL DEFAULT 0,
  `exclure_statistiques` tinyint(1) NOT NULL DEFAULT 0,
  `image_url` varchar(500) DEFAULT NULL,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_article` (`code_article`),
  KEY `fk_articles_unite_secondaire` (`unite_secondaire_id`),
  KEY `fk_articles_createur` (`cree_par`),
  KEY `fk_articles_modificateur` (`modifie_par`),
  KEY `fk_articles_supprimeur` (`supprime_par`),
  KEY `idx_famille` (`famille_id`),
  KEY `idx_type_article` (`type_article`),
  KEY `idx_unite` (`unite_id`),
  KEY `idx_tva` (`tva_id`),
  KEY `idx_actif` (`actif`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_articles_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_articles_famille` FOREIGN KEY (`famille_id`) REFERENCES `d_familles` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_articles_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_articles_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_articles_tva` FOREIGN KEY (`tva_id`) REFERENCES `p_tvas` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_articles_unite` FOREIGN KEY (`unite_id`) REFERENCES `p_unites` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_articles_unite_secondaire` FOREIGN KEY (`unite_secondaire_id`) REFERENCES `p_unites` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_documents definition

CREATE TABLE `d_documents` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `type_document_id` bigint(20) unsigned NOT NULL,
  `code_document` varchar(50) NOT NULL,
  `autre_code_document` varchar(50) NOT NULL,
  `document_origine_id` bigint(20) unsigned DEFAULT NULL,
  `tier_id` bigint(20) unsigned DEFAULT NULL,
  `adresse_livraison_id` bigint(20) unsigned DEFAULT NULL,
  `utilisateur_id` bigint(20) unsigned DEFAULT NULL,
  `vendeur_id` bigint(20) unsigned DEFAULT NULL,
  `montant_ht` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_remise` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_net_ht` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_tva` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_ttc` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_net_ttc` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_paye` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_restant` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `statut_document_id` bigint(20) unsigned NOT NULL,
  `document_valide` tinyint(1) NOT NULL DEFAULT 0,
  `document_cloture` tinyint(1) NOT NULL DEFAULT 0,
  `date_document` datetime NOT NULL,
  `date_livraison_prevue` datetime DEFAULT NULL,
  `date_livraison_effective` datetime DEFAULT NULL,
  `transforme` int(11) NOT NULL DEFAULT 0,
  `date_transforme` datetime DEFAULT NULL,
  `commentaire` text DEFAULT NULL,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_document_reference` (`type_document_id`,`code_document`),
  KEY `fk_documents_origine` (`document_origine_id`),
  KEY `fk_documents_adresse_livraison` (`adresse_livraison_id`),
  KEY `fk_documents_utilisateur` (`utilisateur_id`),
  KEY `fk_documents_vendeur` (`vendeur_id`),
  KEY `fk_documents_createur` (`cree_par`),
  KEY `fk_documents_modificateur` (`modifie_par`),
  KEY `fk_documents_supprimeur` (`supprime_par`),
  KEY `idx_type_document` (`type_document_id`),
  KEY `idx_tier` (`tier_id`),
  KEY `idx_statut` (`statut_document_id`),
  KEY `idx_date_document` (`date_document`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_documents_adresse_livraison` FOREIGN KEY (`adresse_livraison_id`) REFERENCES `d_adresses_livraison` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_documents_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_documents_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_documents_origine` FOREIGN KEY (`document_origine_id`) REFERENCES `d_documents` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_documents_statut` FOREIGN KEY (`statut_document_id`) REFERENCES `p_statuts_documents` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_documents_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_documents_tier` FOREIGN KEY (`tier_id`) REFERENCES `d_tiers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_documents_type` FOREIGN KEY (`type_document_id`) REFERENCES `p_types_documents` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_documents_utilisateur` FOREIGN KEY (`utilisateur_id`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_documents_vendeur` FOREIGN KEY (`vendeur_id`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=121 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_lots_sn definition

CREATE TABLE `d_lots_sn` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `article_id` bigint(20) unsigned NOT NULL,
  `numero_lot_sn` varchar(100) NOT NULL,
  `date_fabrication` date DEFAULT NULL,
  `date_peremption` date DEFAULT NULL,
  `quantite_initiale` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `quantite_actuelle` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `prix_achat_unitaire` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `depot_id` bigint(20) unsigned NOT NULL,
  `fournisseur_id` bigint(20) unsigned DEFAULT NULL,
  `document_entree_id` bigint(20) unsigned DEFAULT NULL,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_lot_article_depot` (`article_id`,`depot_id`,`numero_lot_sn`),
  KEY `fk_lots_document_entree` (`document_entree_id`),
  KEY `fk_lots_createur` (`cree_par`),
  KEY `fk_lots_modificateur` (`modifie_par`),
  KEY `fk_lots_supprimeur` (`supprime_par`),
  KEY `idx_article` (`article_id`),
  KEY `idx_depot` (`depot_id`),
  KEY `idx_fournisseur` (`fournisseur_id`),
  KEY `idx_date_peremption` (`date_peremption`),
  KEY `idx_actif` (`actif`),
  CONSTRAINT `fk_lots_article` FOREIGN KEY (`article_id`) REFERENCES `d_articles` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_lots_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lots_depot` FOREIGN KEY (`depot_id`) REFERENCES `p_depots` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_lots_document_entree` FOREIGN KEY (`document_entree_id`) REFERENCES `d_documents` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lots_fournisseur` FOREIGN KEY (`fournisseur_id`) REFERENCES `d_tiers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lots_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lots_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_projets definition

CREATE TABLE `d_projets` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_projet` varchar(100) NOT NULL,
  `nom_projet` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `tier_id` bigint(20) unsigned DEFAULT NULL,
  `utilisateur_id` bigint(20) unsigned DEFAULT NULL,
  `date_debut` date DEFAULT NULL,
  `date_fin_prevue` date DEFAULT NULL,
  `date_fin_reelle` date DEFAULT NULL,
  `priorite` enum('BASSE','NORMALE','HAUTE','URGENTE') NOT NULL DEFAULT 'NORMALE',
  `budget_prevu` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `budget_reel` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_facture` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `notes` text DEFAULT NULL,
  `actif` tinyint(1) NOT NULL DEFAULT 1,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_projet` (`code_projet`),
  KEY `fk_projets_createur` (`cree_par`),
  KEY `fk_projets_modificateur` (`modifie_par`),
  KEY `fk_projets_supprimeur` (`supprime_par`),
  KEY `idx_tier` (`tier_id`),
  KEY `idx_utilisateur` (`utilisateur_id`),
  KEY `idx_priorite` (`priorite`),
  KEY `idx_actif` (`actif`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_projets_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_projets_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_projets_responsable` FOREIGN KEY (`utilisateur_id`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_projets_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_projets_tier` FOREIGN KEY (`tier_id`) REFERENCES `d_tiers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_reglements definition

CREATE TABLE `d_reglements` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code_reglement` varchar(100) NOT NULL,
  `utilisateur_id` bigint(20) unsigned DEFAULT NULL,
  `tier_id` bigint(20) unsigned NOT NULL,
  `date_reglement` datetime NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `sens_reglement` enum('ENTREE','SORTIE') NOT NULL,
  `mode_reglement_id` bigint(20) unsigned DEFAULT NULL,
  `devise_id` bigint(20) unsigned DEFAULT NULL,
  `taux_change` decimal(18,6) NOT NULL DEFAULT 1.000000,
  `montant_total` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_devise` decimal(18,6) DEFAULT NULL,
  `montant_affecte` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_restant` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_commission` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_net` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `caisse_id` bigint(20) unsigned DEFAULT NULL,
  `reference_piece` varchar(100) DEFAULT NULL,
  `date_echeance` datetime DEFAULT NULL,
  `statut_reglement` enum('BROUILLON','VALIDE','IMPUTE_PARTIEL','IMPUTE_TOTAL','ANNULE','IMPAYE') NOT NULL DEFAULT 'BROUILLON',
  `est_impute` tinyint(1) NOT NULL DEFAULT 0,
  `date_impaye` datetime DEFAULT NULL,
  `cloture` tinyint(1) NOT NULL DEFAULT 0,
  `valide` tinyint(1) NOT NULL DEFAULT 0,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_reglement` (`code_reglement`),
  KEY `fk_reglements_createur` (`cree_par`),
  KEY `fk_reglements_modificateur` (`modifie_par`),
  KEY `fk_reglements_supprimeur` (`supprime_par`),
  KEY `idx_tier` (`tier_id`),
  KEY `idx_utilisateur` (`utilisateur_id`),
  KEY `idx_mode_reglement` (`mode_reglement_id`),
  KEY `idx_devise` (`devise_id`),
  KEY `idx_caisse` (`caisse_id`),
  KEY `idx_date_reglement` (`date_reglement`),
  KEY `idx_statut_reglement` (`statut_reglement`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_reglements_caisse` FOREIGN KEY (`caisse_id`) REFERENCES `p_caisses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_reglements_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_reglements_devise` FOREIGN KEY (`devise_id`) REFERENCES `p_devises` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_reglements_mode` FOREIGN KEY (`mode_reglement_id`) REFERENCES `p_modes_reglement` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_reglements_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_reglements_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_reglements_tier` FOREIGN KEY (`tier_id`) REFERENCES `d_tiers` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_reglements_utilisateur` FOREIGN KEY (`utilisateur_id`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_stock definition

CREATE TABLE `d_stock` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `article_id` bigint(20) unsigned NOT NULL,
  `depot_id` bigint(20) unsigned NOT NULL,
  `quantite_stock` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `quantite_reservee` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `quantite_disponible` decimal(18,4) GENERATED ALWAYS AS (`quantite_stock` - `quantite_reservee`) STORED,
  `cout_moyen` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `date_dernier_mouvement` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_stock_article_depot` (`article_id`,`depot_id`),
  KEY `idx_article` (`article_id`),
  KEY `idx_depot` (`depot_id`),
  CONSTRAINT `fk_stock_article` FOREIGN KEY (`article_id`) REFERENCES `d_articles` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_stock_depot` FOREIGN KEY (`depot_id`) REFERENCES `p_depots` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=199 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_document_lignes definition

CREATE TABLE `d_document_lignes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `document_id` bigint(20) unsigned NOT NULL,
  `numero_ligne` int(10) unsigned NOT NULL,
  `article_id` bigint(20) unsigned DEFAULT NULL,
  `code_article` varchar(100) DEFAULT NULL,
  `designation` varchar(500) DEFAULT NULL,
  `type_ligne` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `quantite` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `unite_id` bigint(20) unsigned DEFAULT NULL,
  `tva_id` bigint(20) unsigned DEFAULT NULL,
  `code_tva` varchar(20) NOT NULL,
  `tva_percentage` decimal(5,2) NOT NULL DEFAULT 0.00,
  `remise_percentage` decimal(5,2) NOT NULL DEFAULT 0.00,
  `prix_unitaire_ht` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `prix_unitaire_ttc` decimal(18,6) GENERATED ALWAYS AS (`prix_unitaire_ht` * (1 + `tva_percentage` / 100)) STORED,
  `prix_unitaire_net_ht` decimal(18,6) GENERATED ALWAYS AS (`prix_unitaire_ht` - `prix_unitaire_ht` * `remise_percentage` / 100) STORED,
  `prix_unitaire_net_ttc` decimal(18,6) GENERATED ALWAYS AS (`prix_unitaire_ttc` - `prix_unitaire_ttc` * `remise_percentage` / 100) STORED,
  `prix_revient_unitaire` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `derniere_prix_achat` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `unitaire_remise` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `unitaire_marge` decimal(18,6) GENERATED ALWAYS AS (`prix_unitaire_net_ht` - `prix_revient_unitaire`) STORED,
  `unitaire_tva` decimal(5,2) GENERATED ALWAYS AS (`prix_unitaire_ht` * `tva_percentage` / 100) STORED,
  `montant_ht` decimal(18,6) GENERATED ALWAYS AS (`quantite` * `prix_unitaire_ht`) STORED,
  `montant_ttc` decimal(18,6) GENERATED ALWAYS AS (`quantite` * `prix_unitaire_ttc`) STORED,
  `montant_net_ht` decimal(18,6) GENERATED ALWAYS AS (`quantite` * `prix_unitaire_net_ht`) STORED,
  `montant_net_ttc` decimal(18,6) GENERATED ALWAYS AS (`quantite` * `prix_unitaire_net_ttc`) STORED,
  `montant_remise` decimal(18,6) GENERATED ALWAYS AS (`quantite` * `unitaire_remise`) STORED,
  `montant_marge` decimal(18,6) GENERATED ALWAYS AS (`quantite` * `unitaire_marge`) STORED,
  `montant_tva` decimal(18,6) GENERATED ALWAYS AS (`quantite` * `unitaire_tva`) STORED,
  `depot_id` bigint(20) unsigned DEFAULT NULL,
  `impact_stock` tinyint(1) NOT NULL DEFAULT 1,
  `valorise_stock` tinyint(1) NOT NULL DEFAULT 1,
  `ligne_source_id` bigint(20) unsigned DEFAULT NULL,
  `document_source_id` bigint(20) unsigned DEFAULT NULL,
  `projet_id` bigint(20) unsigned DEFAULT NULL,
  `date_livraison_prevue` datetime DEFAULT NULL,
  `date_livraison_effective` datetime DEFAULT NULL,
  `transforme` int(11) NOT NULL DEFAULT 0,
  `date_transforme` datetime DEFAULT NULL,
  `numero_lot_sn` varchar(100) DEFAULT NULL,
  `date_peremption` date DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_document_numero_ligne` (`document_id`,`numero_ligne`),
  KEY `fk_lignes_tva` (`tva_id`),
  KEY `fk_lignes_ligne_source` (`ligne_source_id`),
  KEY `fk_lignes_document_source` (`document_source_id`),
  KEY `fk_lignes_createur` (`cree_par`),
  KEY `fk_lignes_modificateur` (`modifie_par`),
  KEY `fk_lignes_supprimeur` (`supprime_par`),
  KEY `idx_document` (`document_id`),
  KEY `idx_article` (`article_id`),
  KEY `idx_unite` (`unite_id`),
  KEY `idx_depot` (`depot_id`),
  KEY `idx_projet` (`projet_id`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_lignes_article` FOREIGN KEY (`article_id`) REFERENCES `d_articles` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lignes_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lignes_depot` FOREIGN KEY (`depot_id`) REFERENCES `p_depots` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lignes_document` FOREIGN KEY (`document_id`) REFERENCES `d_documents` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_lignes_document_source` FOREIGN KEY (`document_source_id`) REFERENCES `d_documents` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lignes_ligne_source` FOREIGN KEY (`ligne_source_id`) REFERENCES `d_document_lignes` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lignes_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lignes_projet` FOREIGN KEY (`projet_id`) REFERENCES `d_projets` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lignes_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lignes_tva` FOREIGN KEY (`tva_id`) REFERENCES `p_tvas` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_lignes_unite` FOREIGN KEY (`unite_id`) REFERENCES `p_unites` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=361 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_document_reglements definition

CREATE TABLE `d_document_reglements` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `document_id` bigint(20) unsigned NOT NULL,
  `reglement_id` bigint(20) unsigned NOT NULL,
  `date_liaison` timestamp NOT NULL DEFAULT current_timestamp(),
  `montant_affecte` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `montant_affecte_devise` decimal(18,6) DEFAULT NULL,
  `regle` tinyint(1) NOT NULL DEFAULT 0,
  `type_affectation` enum('ACOMPTE','REGLEMENT','AVANCE','AVOIR','ECART') NOT NULL DEFAULT 'REGLEMENT',
  `description` varchar(255) DEFAULT NULL,
  `utilisateur_id` bigint(20) unsigned DEFAULT NULL,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_document_reglement` (`document_id`,`reglement_id`),
  KEY `fk_document_reglements_utilisateur` (`utilisateur_id`),
  KEY `fk_document_reglements_createur` (`cree_par`),
  KEY `fk_document_reglements_modificateur` (`modifie_par`),
  KEY `fk_document_reglements_supprimeur` (`supprime_par`),
  KEY `idx_document` (`document_id`),
  KEY `idx_reglement` (`reglement_id`),
  KEY `idx_date_liaison` (`date_liaison`),
  KEY `idx_type_affectation` (`type_affectation`),
  KEY `idx_supprime` (`supprime`),
  CONSTRAINT `fk_document_reglements_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_document_reglements_document` FOREIGN KEY (`document_id`) REFERENCES `d_documents` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_document_reglements_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_document_reglements_reglement` FOREIGN KEY (`reglement_id`) REFERENCES `d_reglements` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_document_reglements_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_document_reglements_utilisateur` FOREIGN KEY (`utilisateur_id`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- azenz_commercial_1.d_mouvements_stock definition

CREATE TABLE `d_mouvements_stock` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `article_id` bigint(20) unsigned NOT NULL,
  `depot_id` bigint(20) unsigned NOT NULL,
  `document_id` bigint(20) unsigned DEFAULT NULL,
  `document_ligne_id` bigint(20) unsigned DEFAULT NULL,
  `type_mouvement` enum('ENTREE','SORTIE','TRANSFERT','AJUSTEMENT','INVENTAIRE') NOT NULL,
  `sens_mouvement` enum('IN','OUT') NOT NULL,
  `quantite` decimal(18,4) NOT NULL,
  `prix_revient_unitaire` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `date_mouvement` datetime NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `cree_par` bigint(20) unsigned DEFAULT NULL,
  `date_creation` timestamp NOT NULL DEFAULT current_timestamp(),
  `modifie_par` bigint(20) unsigned DEFAULT NULL,
  `date_modification` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `supprime` tinyint(1) NOT NULL DEFAULT 0,
  `supprime_par` bigint(20) unsigned DEFAULT NULL,
  `date_suppression` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_mouvements_createur` (`cree_par`),
  KEY `fk_mouvements_modificateur` (`modifie_par`),
  KEY `fk_mouvements_supprimeur` (`supprime_par`),
  KEY `idx_article` (`article_id`),
  KEY `idx_depot` (`depot_id`),
  KEY `idx_document` (`document_id`),
  KEY `idx_document_ligne` (`document_ligne_id`),
  KEY `idx_type_mouvement` (`type_mouvement`),
  KEY `idx_date_mouvement` (`date_mouvement`),
  CONSTRAINT `fk_mouvements_article` FOREIGN KEY (`article_id`) REFERENCES `d_articles` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_mouvements_createur` FOREIGN KEY (`cree_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_mouvements_depot` FOREIGN KEY (`depot_id`) REFERENCES `p_depots` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_mouvements_document` FOREIGN KEY (`document_id`) REFERENCES `d_documents` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_mouvements_document_ligne` FOREIGN KEY (`document_ligne_id`) REFERENCES `d_document_lignes` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_mouvements_modificateur` FOREIGN KEY (`modifie_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_mouvements_supprimeur` FOREIGN KEY (`supprime_par`) REFERENCES `p_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=241 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS = 1;